name: star_trek_facts
description: A Flutter app with login, network check and Star Trek facts.

publish_to: 'none' # Remove this line if you are publishing to pub.dev

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.3
  json_annotation: ^4.7.0
  provider: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

